on:
  push:
    tags:
      - "v*.*.*"

name: Build and Release

jobs:
  build-releases:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust-toolchain: [stable]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          components: rustfmt
          override: true

      - name: Install cross-compilation tools
        run: cargo install cross

      - name: Verify versions
        run: rustc --version && rustup --version && cargo --version && cross --version

      - name: Get current tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: v0.0.0

      - name: Release binaries
        run: ./scripts/release_binaries.sh --version=${{ steps.current_tag.outputs.tag }}

      - name: Release new version
        uses: softprops/action-gh-release@v1
        with:
          name: Vigil Local ${{ steps.current_tag.outputs.tag }}
          body: "⚠️ Changelog not yet provided."
          files: |
            ./${{ steps.current_tag.outputs.tag }}-x86_64.tar.gz
            ./${{ steps.current_tag.outputs.tag }}-armv7.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
